name: Build HTML5 Web Port
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Haxe Environment
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Build Systems
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel 5.5.0 --quiet
          haxelib install flixel-addons 3.2.1 --quiet
          haxelib install flixel-ui 2.6.4 --quiet
          haxelib git hscript-iris https://github.com
          haxelib git polymod https://github.com
          haxelib run lime setup

      - name: Compile to Web Port
        run: haxelib run lime build html5
